allowBuilds:
  sharp: true
  puppeteer: true
  esbuild: true
  workerd: true
minimumReleaseAgeExclude:
  - miniflare@5.20260804.0-alpha
  - wrangler@4.120.1
  - '@biomejs/biome@2.5.8'
  - '@biomejs/cli-darwin-arm64@2.5.8'
  - '@biomejs/cli-darwin-x64@2.5.8'
  - '@biomejs/cli-linux-arm64-musl@2.5.8'
  - '@biomejs/cli-linux-arm64@2.5.8'
  - '@biomejs/cli-linux-x64-musl@2.5.8'
  - '@biomejs/cli-linux-x64@2.5.8'
  - '@biomejs/cli-win32-arm64@2.5.8'
  - '@biomejs/cli-win32-x64@2.5.8'
